#define BASE_ADDR          XPAR_AXI_STATIC_REGISTER_0_BASEADDR

#define REG_CTRL_WR_ADDR          XPAR_AXI_STATIC_REGISTER_0_BASEADDR
#define REG_ALTI_WR_ADDR            XPAR_AXI_STATIC_REGISTER_0_BASEADDR + 0x0004
#define REG_SPED_WR_ADDR            XPAR_AXI_STATIC_REGISTER_0_BASEADDR + 0x0008
#define REG_TPCH_WR_ADDR            XPAR_AXI_STATIC_REGISTER_0_BASEADDR + 0x000C
#define REG_HEAD_WR_ADDR            XPAR_AXI_STATIC_REGISTER_0_BASEADDR + 0x0010
#define REG_PVLT_WR_ADDR            XPAR_AXI_STATIC_REGISTER_0_BASEADDR + 0x0014
#define REG_RVLT_WR_ADDR            XPAR_AXI_STATIC_REGISTER_0_BASEADDR + 0x0018
#define REG_YVLT_WR_ADDR            XPAR_AXI_STATIC_REGISTER_0_BASEADDR + 0x001C

#define REG_THRT_R_ADDR            XPAR_AXI_STATIC_REGISTER_0_BASEADDR + 0x0080
#define REG_CPCH_R_ADDR            XPAR_AXI_STATIC_REGISTER_0_BASEADDR + 0x0084
#define REG_ROLL_R_ADDR            XPAR_AXI_STATIC_REGISTER_0_BASEADDR + 0x0088
#define REG_CYAW_R_ADDR            XPAR_AXI_STATIC_REGISTER_0_BASEADDR + 0x008C
